import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')
const schemaPath = path.join(rootDir, 'prisma', 'schema.prisma')
const outputPath = path.join(rootDir, 'src', 'types', 'prisma.d.ts')

interface Field {
  name: string
  type: string
  isOptional: boolean
  isList: boolean
  isRelation: boolean
}

interface Model {
  name: string
  fields: Field[]
}

interface Enum {
  name: string
  values: string[]
}

function parseSchema(content: string): { models: Model[]; enums: Enum[] } {
  const models: Model[] = []
  const enums: Enum[] = []

  const lines = content.split('\n')
  let currentModel: Model | null = null
  let currentEnum: Enum | null = null

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()

    if (line.startsWith('enum ') && line.includes('{')) {
      const name = line.replace('enum ', '').replace('{', '').trim()
      currentEnum = { name, values: [] }
      continue
    }

    if (currentEnum) {
      if (line === '}') {
        enums.push(currentEnum)
        currentEnum = null
      } else if (line && !line.startsWith('//')) {
        currentEnum.values.push(line.replace(',', '').trim())
      }
      continue
    }

    if (line.startsWith('model ')) {
      const name = line.replace('model ', '').replace('{', '').trim()
      currentModel = { name, fields: [] }
      continue
    }

    if (currentModel) {
      if (line === '}') {
        models.push(currentModel)
        currentModel = null
        continue
      }

      if (line && !line.startsWith('//') && !line.startsWith('@@')) {
        const field = parseField(line)
        if (field) {
          currentModel.fields.push(field)
        }
      }
    }
  }

  return { models, enums }
}

function parseField(line: string): Field | null {
  if (line.includes('@relation') || line.includes('@@')) return null
  if (line.includes('[]')) return null

  const match = line.match(/^(\w+)\s+(\w+)(\?)?(\[\])?(.*)$/)
  if (!match) return null

  const [, name, type, isOptional, isList] = match
  const rest = match[5] || ''

  const isRelation = rest.includes('@relation') || rest.includes('[]')

  return {
    name,
    type: mapPrismaType(type),
    isOptional: isOptional === '?',
    isList: isList === '[]',
    isRelation,
  }
}

function mapPrismaType(prismaType: string): string {
  const typeMap: Record<string, string> = {
    String: 'string',
    Int: 'number',
    Boolean: 'boolean',
    DateTime: 'Date',
    Float: 'number',
    Json: 'object',
    BigInt: 'bigint',
    Bytes: 'Buffer',
  }

  if (typeMap[prismaType]) {
    return typeMap[prismaType]
  }

  return 'string'
}

function generateTypes(models: Model[], enums: Enum[]): string {
  const output: string[] = []
  const enumNames = enums.map((e) => e.name)

  output.push('// Auto-generated by scripts/generate-prisma-types.ts')
  output.push('// DO NOT EDIT - run `pnpm generate:types` to regenerate')
  output.push('')

  for (const enum_ of enums) {
    output.push(`export type ${enum_.name} = ${enum_.values.map((v) => `'${v}'`).join(' | ')}`)
  }
  output.push('')

  for (const model of models) {
    const interfaceFields = model.fields
      .filter((f) => !f.isRelation)
      .map((f) => {
        const rawType = f.type.replace(/s$/, '').replace(/Model$/, '')
        const typeName = enumNames.includes(rawType) ? rawType : f.type
        return `  ${f.name}${f.isOptional ? '?' : ''}: ${typeName}`
      })
      .join('\n')

    output.push(`export interface ${model.name}Model {`)
    output.push(interfaceFields || '  // No non-relation fields')
    output.push('}')
    output.push('')
  }

  const prismaClientMethods = models
    .map((model) => {
      const name = model.name.toLowerCase()
      return `  ${name}: {
    findUnique: (args: { where: { id: string } | { [key: string]: any } }) => Promise<${model.name}Model | null>
    findFirst: (args: any) => Promise<${model.name}Model | null>
    findMany: (args?: any) => Promise<${model.name}Model[]>
    create: (args: { data: any }) => Promise<${model.name}Model>
    update: (args: { where: any; data: any }) => Promise<${model.name}Model>
    delete: (args: { where: { id: string } }) => Promise<${model.name}Model>
    updateMany: (args: any) => Promise<{ count: number }>
    deleteMany: (args: any) => Promise<{ count: number }>
  }`
    })
    .join('\n')

  output.push('export interface PrismaClient {')
  output.push(prismaClientMethods)
  output.push('  $connect: () => Promise<void>')
  output.push('  $disconnect: () => Promise<void>')
  output.push('}')

  return output.join('\n')
}

async function main() {
  console.log('Reading schema from:', schemaPath)

  const content = fs.readFileSync(schemaPath, 'utf-8')
  const { models, enums } = parseSchema(content)

  console.log(`Found ${models.length} models, ${enums.length} enums`)

  const types = generateTypes(models, enums)
  fs.writeFileSync(outputPath, types, 'utf-8')

  console.log('Generated:', outputPath)
}

main().catch(console.error)
